name: Lint GitHub Actions workflow

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  lint:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/gha.yml@eeb0b9b795d7bf3f962ed0f585ac729264d0fcdd
