name: Validate Renovate config

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json

jobs:
  validate:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/renovate.yml@eeb0b9b795d7bf3f962ed0f585ac729264d0fcdd
